version: '3.8'
services:
  general-app:
    image: general-app:latest
    container_name: general-app-frontend
    restart: always
    ports:
      - '3010:3000'
    networks:
      - coursebee
networks:
  coursebee:
    driver: bridge
