export const categoryMap = new Map();
categoryMap.set('coding', { en: "Coding", bn: "কোডিং" });
categoryMap.set('job_based', { en: "Job Based", bn: "চাকরি ভিত্তিক" });
categoryMap.set('research', { en: "Research", bn: "গবেষণা" });
categoryMap.set('practical', { en: "Practical", bn: "ব্যবহারিক" });
categoryMap.set('quick_learn', { en: "Quick Learn", bn: "দ্রুত শিখুন" });
categoryMap.set('editorial', { en: "Editorial", bn: "সম্পাদকীয়" });
categoryMap.set('enhancer', { en: "Enhancer", bn: "বৃদ্ধিকারী" });


export const courses_bn = [
    {
      title: 'Full-Stack Mastery',
      subtitle: 'Building with MERN',
      desc: 'MERN স্ট্যাকের শক্তি আনলক করুন এবং হ্যান্ড-অন প্রোজেক্ট এবং ব্যাপক প্রশিক্ষণ সহ একজন দক্ষ ফুল-স্ট্যাক বিকাশকারী হয়ে উঠুন।',
      cover: '/images/courses/thumbnails/course-1.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn, categoryMap.get('job_based').bn, categoryMap.get('practical').bn],
      rating: 4,
    },
    {
      title: 'Python Powerhouse',
      subtitle: 'Unlocking Its Full Potential',
      desc: 'পাইথনের শক্তি উন্মোচন করুন: শক্তিশালী অ্যাপ্লিকেশন তৈরি করুন এবং এই বহুমুখী প্রোগ্রামিং ভাষার সাথে জটিল সমস্যার সমাধান করুন।',
      cover: '/images/courses/thumbnails/course-2.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn, categoryMap.get('job_based').bn, categoryMap.get('practical').bn],
      rating: 5,
    },
    {
      title: 'Web Design Unleashed',
      subtitle: 'Creating Digital Experiences',
      desc: 'আপনার সৃজনশীলতা প্রকাশ করুন এবং চিত্তাকর্ষক ডিজিটাল অভিজ্ঞতা তৈরি করতে দক্ষতা অর্জন করুন যা স্থায়ী প্রভাব ফেলে।',
      cover: '/images/courses/thumbnails/course-3.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').bn, categoryMap.get('practical').bn, categoryMap.get('editorial').bn],
      rating: 4,
    },
    {
      title: 'WordPress Wizardry',
      subtitle: 'Crafting Dynamic Websites',
      desc: 'চোখ ধাঁধানো পণ্যগুলিকে একত্রিত করে সৃজনশীলতা এবং কার্যকারিতাকে নির্বিঘ্নে মিশ্রিত করে এমন গতিশীল ওয়েবসাইটগুলি তৈরি করার শিল্পে আয়ত্ত করুন৷',
      cover: '/images/courses/thumbnails/course-5.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').bn, categoryMap.get('practical').bn, categoryMap.get('quick_learn').bn],
      rating: 3,
    },
    {
      title: 'User-Centric Design',
      subtitle: 'Mastering UI/UX',
      desc: 'স্বজ্ঞাত ইন্টারফেস তৈরির শিল্পে আয়ত্ত করে নিরবচ্ছিন্ন এবং ব্যবহারকারী-কেন্দ্রিক ডিজিটাল অভিজ্ঞতা তৈরি করতে UI/UX ডিজাইনের নীতিগুলি আয়ত্ত করুন।',
      cover: '/images/courses/thumbnails/course-4.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').bn, categoryMap.get('practical').bn, categoryMap.get('editorial').bn],
      rating: 3.5,
    },
    {
      title: 'Visual Communication',
      subtitle: 'Mastering Graphics Design',
      desc: 'চাক্ষুষ যোগাযোগের শক্তি আনলক করুন এবং গ্রাফিক্স ডিজাইনের শিল্পে আয়ত্ত করুন, কীভাবে কার্যকরভাবে বার্তাগুলি প্রকাশ করতে হয় তা শিখুন',
      cover: '/images/courses/thumbnails/course-6.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').bn, categoryMap.get('practical').bn, categoryMap.get('editorial').bn],
      rating: 4.5,
    },
    {
      title: 'Cinematic Storytelling',
      subtitle: 'Mastering Video Editing',
      desc: 'সিনেম্যাটিক গল্প বলার জগতে নিজেকে নিমজ্জিত করুন এবং ভিডিও সম্পাদনার শিল্পে আয়ত্ত করুন, আকর্ষক গল্প তৈরি করার দক্ষতা অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-7.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').bn, 'Enhancer', categoryMap.get('practical').bn, categoryMap.get('editorial').bn],
      rating: 4,
    },
    {
      title: 'Ethical Hacking Unveiled',
      subtitle: 'Securing the Digital Realm',
      desc: 'সিনেম্যাটিক গল্প বলার জগতে নিজেকে নিমজ্জিত করুন এবং ভিডিও সম্পাদনার শিল্পে আয়ত্ত করুন, আকর্ষক গল্প তৈরি করার দক্ষতা অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-8.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn, categoryMap.get('research').bn, categoryMap.get('practical').bn, categoryMap.get('job_based').bn],
      rating: 3.5,
    },
    {
      title: 'Machine Learning Insights',
      subtitle: 'Mastering Data Analysis',
      desc: 'মেশিন লার্নিং এর জগতে প্রবেশ করুন এবং ডেটা বিশ্লেষণে দক্ষতা অর্জন, প্রয়োজনীয় দক্ষতা অর্জনের জন্য মূল্যবান অন্তর্দৃষ্টি অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-9.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn, categoryMap.get('research').bn],
      rating: 4,
    },
    {
      title: 'Data Science Demystified',
      subtitle: 'Empowering Everyone',
      desc: 'ডেটা সায়েন্সের জগৎকে বিকৃত করুন এবং ডেটা ব্যবহার করার দক্ষতা ও জ্ঞান দিয়ে নিজেকে শক্তিশালী করুন।',
      cover: '/images/courses/thumbnails/course-11.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').bn, categoryMap.get('research').bn],
      rating: 3,
    },
    {
      title: 'Digital Marketing Domination',
      subtitle: 'Strategies for Success',
      desc: 'ডিজিটাল মার্কেটিং এর ক্ষেত্র জয় করুন এবং সফলতার জন্য কার্যকরী কৌশলের উপর আয়ত্ত অর্জন করুন, শক্তিশালী কৌশল আবিষ্কার করুন',
      cover: '/images/courses/thumbnails/course-10.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('editorial').bn, categoryMap.get('quick_learn').bn],
      rating: 3.5,
    },
  
    {
      title: 'Building Digital Ventures',
      subtitle: 'Digital Enterprise Opportunities',
      desc: 'ডিজিটাল উদ্যোগ গড়ে তোলার যাত্রা শুরু করুন এবং জ্ঞান অর্জন করে ডিজিটাল এন্টারপ্রাইজ ল্যান্ডস্কেপের বিশাল সুযোগগুলি অন্বেষণ করুন।',
      cover: '/images/courses/thumbnails/course-12.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('editorial').bn, categoryMap.get('quick_learn').bn],
      rating: 4.5,
    },
    {
      title: 'React Revolution',
      subtitle: 'Mastering Frontend',
      desc: 'প্রতিক্রিয়া বিপ্লবে যোগ দিন এবং গতিশীল এবং ইন্টারেক্টিভ UI তৈরির শিল্পে দক্ষতা অর্জন করে ফ্রন্টএন্ড বিকাশের একজন মাস্টার হয়ে উঠুন।',
      cover: '/images/courses/thumbnails/course-5.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn, categoryMap.get('job_based').bn],
      rating: 4,
    },
    {
      title: 'Scholar\'s Journey',
      subtitle: 'Research and Publication',
      desc: 'একজন পণ্ডিতের যাত্রা শুরু করুন এবং প্রয়োজনীয় দক্ষতা এবং পদ্ধতিগুলি অর্জন করে সফল গবেষণা এবং প্রকাশনার পথ খুলে দিন।',
      cover: '/images/courses/thumbnails/course-13.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('research').bn, categoryMap.get('editorial').bn],
      rating: 4.5,
    },
    {
      title: 'Flutter Power',
      subtitle: 'Mobile Development',
      desc: 'ফ্লটারের শক্তিকে কাজে লাগান এবং মোবাইল ডেভেলপমেন্টের জগতে ডুব দিন, ক্রস-প্ল্যাটফর্ম অ্যাপ্লিকেশন তৈরির শিল্পে আয়ত্ত করুন।',
      cover: '/images/courses/thumbnails/course-14.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn, categoryMap.get('job_based').bn],
      rating: 3.5,
    },
    {
      title: 'Competitive Programming',
      subtitle: 'Coding with Confidence',
      desc: 'প্রতিযোগিতামূলক প্রোগ্রামিংয়ের যাত্রা শুরু করুন এবং কোডিং চ্যালেঞ্জ, অ্যালগরিদম মাস্টারিং ইত্যাদিতে দক্ষতা অর্জনের জন্য আত্মবিশ্বাস অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-15.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn],
      rating: 4.5,
    },
    {
      title: 'Mastering English Communication',
      subtitle: 'Fluency in Speaking, Writing',
      desc: 'ইংরেজি কমিউনিকেশনে দক্ষতা অর্জনের চাবিকাঠি আনলক করুন এবং কথা বলা এবং লেখা উভয় ক্ষেত্রেই সাবলীলতা অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-16.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').bn, categoryMap.get('quick_learn').bn],
      rating: 3,
    },
    {
      title: 'After-School',
      subtitle: 'Coding Adventures',
      desc: 'স্কুলের পরে কোডিং অ্যাডভেঞ্চার শুরু করুন, যেখানে তরুণ শিক্ষার্থীরা প্রোগ্রামিংয়ের জগতে ডুব দেয়, উত্তেজনাপূর্ণ প্রকল্পগুলি অন্বেষণ করে।',
      cover: '/images/courses/thumbnails/course-21.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn],
      rating: 3,
    },
    {
      title: 'Creative Explorers',
      subtitle: 'Fun and Learning for Kids',
      desc: 'স্একটি সৃজনশীল অন্বেষণ যাত্রা শুরু করুন যা বিশেষভাবে বাচ্চাদের জন্য ডিজাইন করা হয়েছে, একটি মজাদার এবং আকর্ষক শেখার অভিজ্ঞতা প্রদান করে।',
      cover: '/images/courses/thumbnails/course-19.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('editorial').bn, categoryMap.get('quick_learn').bn],
      rating: 3,
    },
    {
      title: 'After-School Robotics',
      subtitle: 'Building the Future',
      desc: 'আমাদের স্কুল-পরবর্তী রোবোটিক্স প্রোগ্রামে আপনার সম্ভাবনা উন্মোচন করুন এবং একটি উজ্জ্বল ভবিষ্যত গড়ে তুলুন রোবোটিক্সের চিত্তাকর্ষক বিশ্ব অন্বেষণ করুন।',
      cover: '/images/courses/thumbnails/course-17.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').bn, categoryMap.get('research').bn, categoryMap.get('practical').bn],
      rating: 3.5,
    },
    {
      title: 'Mastering Effective',
      subtitle: 'Communication Skills',
      desc: 'কার্যকর যোগাযোগের শিল্পে আয়ত্ত করুন এবং স্বচ্ছতা এবং আত্মবিশ্বাসের সাথে নিজেকে প্রকাশ করার শক্তি আনলক করুন।',
      cover: '/images/courses/thumbnails/course-18.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('quick_learn').bn, categoryMap.get('enhancer').bn, categoryMap.get('editorial').bn],
      rating: 0,
    },
  ]
  
  export const courses_en = [
    {
      title: 'Full-Stack Mastery',
      subtitle: 'Building with MERN',
      desc: 'MERN স্ট্যাকের শক্তি আনলক করুন এবং হ্যান্ড-অন প্রোজেক্ট এবং ব্যাপক প্রশিক্ষণ সহ একজন দক্ষ ফুল-স্ট্যাক বিকাশকারী হয়ে উঠুন।',
      cover: '/images/courses/thumbnails/course-1.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en, categoryMap.get('job_based').en, categoryMap.get('practical').en],
      rating: 4,
    },
    {
      title: 'Python Powerhouse',
      subtitle: 'Unlocking Its Full Potential',
      desc: 'পাইথনের শক্তি উন্মোচন করুন: শক্তিশালী অ্যাপ্লিকেশন তৈরি করুন এবং এই বহুমুখী প্রোগ্রামিং ভাষার সাথে জটিল সমস্যার সমাধান করুন।',
      cover: '/images/courses/thumbnails/course-2.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en, categoryMap.get('job_based').en, categoryMap.get('practical').en],
      rating: 5,
    },
    {
      title: 'Web Design Unleashed',
      subtitle: 'Creating Digital Experiences',
      desc: 'আপনার সৃজনশীলতা প্রকাশ করুন এবং চিত্তাকর্ষক ডিজিটাল অভিজ্ঞতা তৈরি করতে দক্ষতা অর্জন করুন যা স্থায়ী প্রভাব ফেলে।',
      cover: '/images/courses/thumbnails/course-3.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').en, categoryMap.get('practical').en, categoryMap.get('editorial').en],
      rating: 4,
    },
    {
      title: 'WordPress Wizardry',
      subtitle: 'Crafting Dynamic Websites',
      desc: 'চোখ ধাঁধানো পণ্যগুলিকে একত্রিত করে সৃজনশীলতা এবং কার্যকারিতাকে নির্বিঘ্নে মিশ্রিত করে এমন গতিশীল ওয়েবসাইটগুলি তৈরি করার শিল্পে আয়ত্ত করুন৷',
      cover: '/images/courses/thumbnails/course-5.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').en, categoryMap.get('practical').en, categoryMap.get('quick_learn').en],
      rating: 3,
    },
    {
      title: 'User-Centric Design',
      subtitle: 'Mastering UI/UX',
      desc: 'স্বজ্ঞাত ইন্টারফেস তৈরির শিল্পে আয়ত্ত করে নিরবচ্ছিন্ন এবং ব্যবহারকারী-কেন্দ্রিক ডিজিটাল অভিজ্ঞতা তৈরি করতে UI/UX ডিজাইনের নীতিগুলি আয়ত্ত করুন।',
      cover: '/images/courses/thumbnails/course-4.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').en, categoryMap.get('practical').en, categoryMap.get('editorial').en],
      rating: 3.5,
    },
    {
      title: 'Visual Communication',
      subtitle: 'Mastering Graphics Design',
      desc: 'চাক্ষুষ যোগাযোগের শক্তি আনলক করুন এবং গ্রাফিক্স ডিজাইনের শিল্পে আয়ত্ত করুন, কীভাবে কার্যকরভাবে বার্তাগুলি প্রকাশ করতে হয় তা শিখুন',
      cover: '/images/courses/thumbnails/course-6.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').en, categoryMap.get('practical').en, categoryMap.get('editorial').en],
      rating: 4.5,
    },
    {
      title: 'Cinematic Storytelling',
      subtitle: 'Mastering Video Editing',
      desc: 'সিনেম্যাটিক গল্প বলার জগতে নিজেকে নিমজ্জিত করুন এবং ভিডিও সম্পাদনার শিল্পে আয়ত্ত করুন, আকর্ষক গল্প তৈরি করার দক্ষতা অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-7.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').en, 'Enhancer', categoryMap.get('practical').en, categoryMap.get('editorial').en],
      rating: 4,
    },
    {
      title: 'Ethical Hacking Unveiled',
      subtitle: 'Securing the Digital Realm',
      desc: 'সিনেম্যাটিক গল্প বলার জগতে নিজেকে নিমজ্জিত করুন এবং ভিডিও সম্পাদনার শিল্পে আয়ত্ত করুন, আকর্ষক গল্প তৈরি করার দক্ষতা অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-8.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en, categoryMap.get('research').en, categoryMap.get('practical').en, categoryMap.get('job_based').en],
      rating: 3.5,
    },
    {
      title: 'Machine Learning Insights',
      subtitle: 'Mastering Data Analysis',
      desc: 'মেশিন লার্নিং এর জগতে প্রবেশ করুন এবং ডেটা বিশ্লেষণে দক্ষতা অর্জন, প্রয়োজনীয় দক্ষতা অর্জনের জন্য মূল্যবান অন্তর্দৃষ্টি অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-9.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en, categoryMap.get('research').en],
      rating: 4,
    },
    {
      title: 'Data Science Demystified',
      subtitle: 'Empowering Everyone',
      desc: 'ডেটা সায়েন্সের জগৎকে বিকৃত করুন এবং ডেটা ব্যবহার করার দক্ষতা ও জ্ঞান দিয়ে নিজেকে শক্তিশালী করুন।',
      cover: '/images/courses/thumbnails/course-11.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').en, categoryMap.get('research').en],
      rating: 3,
    },
    {
      title: 'Digital Marketing Domination',
      subtitle: 'Strategies for Success',
      desc: 'ডিজিটাল মার্কেটিং এর ক্ষেত্র জয় করুন এবং সফলতার জন্য কার্যকরী কৌশলের উপর আয়ত্ত অর্জন করুন, শক্তিশালী কৌশল আবিষ্কার করুন',
      cover: '/images/courses/thumbnails/course-10.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('editorial').en, categoryMap.get('quick_learn').en],
      rating: 3.5,
    },
  
    {
      title: 'Building Digital Ventures',
      subtitle: 'Digital Enterprise Opportunities',
      desc: 'ডিজিটাল উদ্যোগ গড়ে তোলার যাত্রা শুরু করুন এবং জ্ঞান অর্জন করে ডিজিটাল এন্টারপ্রাইজ ল্যান্ডস্কেপের বিশাল সুযোগগুলি অন্বেষণ করুন।',
      cover: '/images/courses/thumbnails/course-12.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('editorial').en, categoryMap.get('quick_learn').en],
      rating: 4.5,
    },
    {
      title: 'React Revolution',
      subtitle: 'Mastering Frontend',
      desc: 'প্রতিক্রিয়া বিপ্লবে যোগ দিন এবং গতিশীল এবং ইন্টারেক্টিভ UI তৈরির শিল্পে দক্ষতা অর্জন করে ফ্রন্টএন্ড বিকাশের একজন মাস্টার হয়ে উঠুন।',
      cover: '/images/courses/thumbnails/course-5.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en, categoryMap.get('job_based').en],
      rating: 4,
    },
    {
      title: 'Scholar\'s Journey',
      subtitle: 'Research and Publication',
      desc: 'একজন পণ্ডিতের যাত্রা শুরু করুন এবং প্রয়োজনীয় দক্ষতা এবং পদ্ধতিগুলি অর্জন করে সফল গবেষণা এবং প্রকাশনার পথ খুলে দিন।',
      cover: '/images/courses/thumbnails/course-13.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('research').en, categoryMap.get('editorial').en],
      rating: 4.5,
    },
    {
      title: 'Flutter Power',
      subtitle: 'Mobile Development',
      desc: 'ফ্লটারের শক্তিকে কাজে লাগান এবং মোবাইল ডেভেলপমেন্টের জগতে ডুব দিন, ক্রস-প্ল্যাটফর্ম অ্যাপ্লিকেশন তৈরির শিল্পে আয়ত্ত করুন।',
      cover: '/images/courses/thumbnails/course-14.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en, categoryMap.get('job_based').en],
      rating: 3.5,
    },
    {
      title: 'Competitive Programming',
      subtitle: 'Coding with Confidence',
      desc: 'প্রতিযোগিতামূলক প্রোগ্রামিংয়ের যাত্রা শুরু করুন এবংকোডিংচ্যালেঞ্জ, অ্যালগরিদম মাস্টারিং ইত্যাদিতে দক্ষতা অর্জনের জন্য আত্মবিশ্বাস অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-15.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en],
      rating: 4.5,
    },
    {
      title: 'Mastering English Communication',
      subtitle: 'Fluency in Speaking, Writing',
      desc: 'ইংরেজি কমিউনিকেশনে দক্ষতা অর্জনের চাবিকাঠি আনলক করুন এবং কথা বলা এবং লেখা উভয় ক্ষেত্রেই সাবলীলতা অর্জন করুন।',
      cover: '/images/courses/thumbnails/course-16.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('job_based').en, categoryMap.get('quick_learn').en],
      rating: 3,
    },
    {
      title: 'After-School',
      subtitle: 'Coding Adventures',
      desc: 'স্কুলের পরেকোডিংঅ্যাডভেঞ্চার শুরু করুন, যেখানে তরুণ শিক্ষার্থীরা প্রোগ্রামিংয়ের জগতে ডুব দেয়, উত্তেজনাপূর্ণ প্রকল্পগুলি অন্বেষণ করে।',
      cover: '/images/courses/thumbnails/course-21.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en],
      rating: 3,
    },
    {
      title: 'Creative Explorers',
      subtitle: 'Fun and Learning for Kids',
      desc: 'স্একটি সৃজনশীল অন্বেষণ যাত্রা শুরু করুন যা বিশেষভাবে বাচ্চাদের জন্য ডিজাইন করা হয়েছে, একটি মজাদার এবং আকর্ষক শেখার অভিজ্ঞতা প্রদান করে।',
      cover: '/images/courses/thumbnails/course-19.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('editorial').en, categoryMap.get('quick_learn').en],
      rating: 3,
    },
    {
      title: 'After-School Robotics',
      subtitle: 'Building the Future',
      desc: 'আমাদের স্কুল-পরবর্তী রোবোটিক্স প্রোগ্রামে আপনার সম্ভাবনা উন্মোচন করুন এবং একটি উজ্জ্বল ভবিষ্যত গড়ে তুলুন রোবোটিক্সের চিত্তাকর্ষক বিশ্ব অন্বেষণ করুন।',
      cover: '/images/courses/thumbnails/course-17.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('coding').en, categoryMap.get('research').en, categoryMap.get('practical').en],
      rating: 3.5,
    },
    {
      title: 'Mastering Effective',
      subtitle: 'Communication Skills',
      desc: 'কার্যকর যোগাযোগের শিল্পে আয়ত্ত করুন এবং স্বচ্ছতা এবং আত্মবিশ্বাসের সাথে নিজেকে প্রকাশ করার শক্তি আনলক করুন।',
      cover: '/images/courses/thumbnails/course-18.png',
      price: '৪৯৯৯.৯৯',
      category: [categoryMap.get('quick_learn').en, categoryMap.get('enhancer').en, categoryMap.get('editorial').en],
      rating: 0,
    },
  ]
  