version: '3.8'
services:
  student-app:
    image: student-app:latest
    container_name: student-app-frontend
    restart: always
    ports:
      - '3011:3001'
    networks:
      - coursebee
networks:
  coursebee:
    driver: bridge
